spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_lotto_postgres
    username: postgres
    password: 3451
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000