#junsang-aws-database.chl9xl3gtxky.us-east-2.rds.amazonaws.com
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_lotto
    username: postgres
    password: 3451
    driver-class-name: org.postgresql.Driver