server:
  port: 8080

spring:
  application:
    name: spring-lotto-project
  profiles:
    active: local
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cacheDuration: 3
    alwaysUseMessageFormat: true
    useCodeAsDefaultMessage: true
    fallbackToSystemLocale: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dkwnstkddk@gmail.com
    password: ybjv wuyg rckf hyaw
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
    auth-code-expiration-millis: 180000
  logging:
    level:
      org.hibernate.SQL: debug

integration:
  slack:
    enabled: true
    web-hook-url: https://hooks.slack.com/services/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
    channel: error-log
  level: ERROR

junsang:
  jwt:
    secret: junsang_l@tt@
    valid-time: 2h