server:
  port: 8080

spring:
  application:
    name: spring-lotto-project
  profiles:
    active: local
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cacheDuration: 3
    alwaysUseMessageFormat: true
    useCodeAsDefaultMessage: true
    fallbackToSystemLocale: true

  logging:
    level:
      org.hibernate.SQL: debug